# Generated by Django 2.0.1 on 2018-04-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180419_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incategory',
            name='color',
            field=models.CharField(default='88ff88', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='incategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='outcategory',
            name='color',
            field=models.CharField(default='ff8888', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='outcategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
