# Generated by Django 2.0.1 on 2018-04-21 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20180419_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outgoings',
            new_name='Expenses',
        ),
        migrations.RenameModel(
            old_name='Earnings',
            new_name='Incomes',
        ),
    ]
