# Generated by Django 2.0.1 on 2018-05-14 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20180421_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Incomes',
            new_name='Income',
        ),
        migrations.AlterModelOptions(
            name='incategory',
            options={'verbose_name': 'Income Categories'},
        ),
        migrations.AlterModelOptions(
            name='outcategory',
            options={'verbose_name': 'Expense Categories'},
        ),
    ]
