# Generated by Django 2.0.1 on 2018-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180514_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incategory',
            options={'verbose_name': 'Income Categorie'},
        ),
        migrations.AlterModelOptions(
            name='outcategory',
            options={'verbose_name': 'Expense Categorie'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
