# Generated by Django 2.0.1 on 2018-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180609_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='incategory',
            options={'verbose_name': 'Income Category'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='outcategory',
            options={'verbose_name': 'Expense Category'},
        ),
        migrations.AddField(
            model_name='incategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='incategory',
            name='name_uk',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='outcategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='outcategory',
            name='name_uk',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
